# site information
title: Klazerville
description: Just trying to be as great as Manderville.

# site settings
url: ""
baseurl: "/"
repo: https://github.com/haothitran/klazerville

# build settings
include: ["_pages"]

# author information
author:
  name: Hao Tran
  email: hello@haothitran.com
  website: https://haothitran.com/
  git: https://github.com/haothitran/
  discord: Klaz#6060
