site_name: Klazerville
site_description: A reference guide for various aspects of Final Fantasy XIV.
site_url: https://klazerville.com/

nav:
  - Home: index.md
  - General:
    - Checklist: general/checklist.md
    - Jobs: general/jobs.md
    - Gathering and Crafting: general/gathering-and-crafting.md
  - Duties:
    - Dungeons: duties/dungeons.md
    - Trials: duties/trials.md
    - Raids: duties/raids.md

theme:
  favicon: assets/favicon.ico
  icon:
    logo: material/crown

  name: material
  palette:
    scheme: klaz
  custom_dir: overrides

extra_css:
- assets/style.css

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haothitran/klazerville

copyright: >-
  Game content and materials are trademarks and copyrights of Square Enix Co., Ltd.<br>
  To report site problems or suggestions, <a href="https://github.com/haothitran/klazerville/issues">open an issue</a> or contact Klaz#6060 on Discord.
