site_name: Klazerville
site_description: A reference guide for various aspects of Final Fantasy XIV.
site_url: https://klazerville.com/

nav:
  - Home: index.md
  - Checklist: checklist.md
  - Jobs: jobs.md
  - Gathering:
    - Overview: gathering/overview.md
    - Botanist: gathering/botanist.md
    - Fisher: gathering/fisher.md
    - Miner: gathering/miner.md
  - Crafting:
    - Overview: crafting/overview.md
    - Alchemist: crafting/alchemist.md
    - Armorer: crafting/armorer.md
    - Blacksmith: crafting/blacksmith.md
    - Carpenter: crafting/carpenter.md
    - Culinarian: crafting/culinarian.md
    - Goldsmith: crafting/goldsmith.md
    - Leatherworker: crafting/leatherworker.md
    - Weaver: crafting/weaver.md
  - Duties:
    - Dungeons: duties/dungeons.md
    - Trials: duties/trials.md
    - Raids: duties/raids.md

theme:
  favicon: assets/favicon.ico
  icon:
    logo: material/crown

  name: material
  palette:
    scheme: default
    primary: deep purple
    accent: pink
  custom_dir: overrides

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haothitran/klazerville

copyright: >-
  Game content and materials are trademarks and copyrights of Square Enix Co., Ltd.<br>
  To report site problems or suggestions, <a href="https://github.com/haothitran/klazerville/issues">open an issue</a> or contact Klaz#6060 on Discord.
